server:
  port: 8762
  servlet:
    context-path: /storm_oss

spring:
  application:
    name: service-oss
  #多模块配置文件引用
  profiles:
    active: dev
  #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/storm_oss?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456aB
    driver-class-name: com.mysql.jdbc.Driver
  #模板配置
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  #redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1ms
        max-idle: 8

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/