spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1ms
        max-idle: 8
    timeout: 5000ms
    database: 0
